# Generated by Django 4.2.13 on 2024-07-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_question_choice_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
